### ISSUE TITLE
New feature?

### ISSUE THREAD

**Issue by taich001** [alfredbuehler/bookmarks#4]
It would be great to have the possibility to sort bookmarks by name or even better to arange bookmarks in my own order.

How can this be done?
Greetings Thomas

**Comment by alfredbuehler** [comment]
I don't see where sorting can be changed now. It's somewhat 'prepared', but was never implemented. But currently I have no concrete plans to extend bookmarks app in any way.

**Comment by alfredbuehler** [comment]
Closed. Release v0.10.5 implements sorting.
